### ISSUE TITLE
ValueError: Different sample sets found in CLI but not API

### ISSUE THREAD

**Issue by anh151** [sbslee/pypgx#96]
Hello,
I am having an issue that is only occurring using the CLI and not with the API when it comes to sample ids. I've modified the code to print the sample ids for `read_depth.data.samples` and `control_statistics.data.index`

Below is my API code and output
```python
def run_pypgx(bam_file):
    sample_id = re.findall(r"\d{7}", bam_file)[0]
    with tempfile.TemporaryDirectory() as tmpdirname:
        pypgx.create_input_vcf(
            vcf=os.path.join(tmpdirname, f"{sample_id}.vcf.gz"),
            fasta="lib/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna",
            bams=bam_file,
            assembly="GRCh38",
            genes=["CYP2D6"],
        )
        depth_of_coverage = pypgx.prepare_depth_of_coverage(
            bams=bam_file, assembly="GRCh38", genes=["CYP2D6"]
        )
        control_statistics = pypgx.compute_control_statistics(
            gene="EGFR", bams=bam_file, assembly="GRCh38"
        )
        pypgx.run_ngs_pipeline(
            gene="CYP2D6",
            output=tmpdirname,
            variants=os.path.join(tmpdirname, f"{sample_id}.vcf.gz"),
            depth_of_coverage=depth_of_coverage,
            control_statistics=control_statistics,
            assembly="GRCh38",
        )
```
```
Saved VcfFrame[Imported] to: /tmp/tmpbr6x581f/imported-variants.zip
Saved VcfFrame[Phased] to: /tmp/tmpbr6x581f/phased-variants.zip
Saved VcfFrame[Consolidated] to: /tmp/tmpbr6x581f/consolidated-variants.zip
Saved SampleTable[Alleles] to: /tmp/tmpbr6x581f/alleles.zip
Saved CovFrame[ReadDepth] to: /tmp/tmpbr6x581f/read-depth.zip
['0370947305']
Index(['0370947305'], dtype='object')
Saved CovFrame[CopyNumber] to: /tmp/tmpbr6x581f/copy-number.zip
Saved SampleTable[CNVCalls] to: /tmp/tmpbr6x581f/cnv-calls.zip
Saved SampleTable[Genotypes] to: /tmp/tmpbr6x581f/genotypes.zip
Saved SampleTable[Phenotypes] to: /tmp/tmpbr6x581f/phenotypes.zip
Saved SampleTable[Results] to: /tmp/tmpbr6x581f/results.zip

```

Below is the CLI code with output

```bash
pypgx create-input-vcf variants.vcf.gz ./lib/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna filtered_bams/filtered_1000004.bam --assembly GRCh38 --genes CYP2D6

pypgx prepare-depth-of-coverage depth_of_coverage.doc filtered_bams/filtered_1000004.bam --assembly GRCh38 --genes CYP2D6 

pypgx compute-control-statistics CYP2D6 control_statistics.cs filtered_bams/filtered_1000004.bam --assembly GRCh38

pypgx run-ngs-pipeline CYP2D6 pypgx_results/output --variants variants.vcf.gz --depth-of-coverage depth_of_coverage.doc --control-statistics control_statistics.cs --assembly GRCh38  
```

with output of
```
Saved VcfFrame[Imported] to: pypgx_results/output/imported-variants.zip
Saved VcfFrame[Phased] to: pypgx_results/output/phased-variants.zip
Saved VcfFrame[Consolidated] to: pypgx_results/output/consolidated-variants.zip
Saved SampleTable[Alleles] to: pypgx_results/output/alleles.zip
Saved CovFrame[ReadDepth] to: pypgx_results/output/read-depth.zip
['0370947305']
Index(['370947305'], dtype='object')
Traceback (most recent call last):
  File "/home/jupyter/.local/bin/pypgx", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter/.local/lib/python3.7/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/home/jupyter/.local/lib/python3.7/site-packages/pypgx/cli/run_ngs_pipeline.py", line 167, in main
    platform=args.platform, cnv_caller=args.cnv_caller
  File "/home/jupyter/.local/lib/python3.7/site-packages/pypgx/api/pipeline.py", line 289, in run_ngs_pipeline
    control_statistics, samples_without_sv=samples_without_sv)
  File "/home/jupyter/.local/lib/python3.7/site-packages/pypgx/api/utils.py", line 449, in compute_copy_number
    raise ValueError('Different sample sets found')
ValueError: Different sample sets found

```

**Comment by sbslee** [comment]
@anh151,

Thanks for reporting the issue! Which PyPGx version are you currently using? It appears that the issue is related to #78 and this bug has been fixed in `0.20.0`. Please see the [Changelog](https://pypgx.readthedocs.io/en/latest/changelog.html) page and try again using the latest version. Let me know if this doesn't fix the problem!

**Comment by anh151** [comment]
@sbslee 
I am using `0.20.0` and still having the same error.

**Comment by sbslee** [comment]
Thanks for the prompt feedback! I re-opened the issue and will look into it.

It will help me significantly if you can share your `SampleTable[Statsitics]` and `CovFrame[ReadDepth]` files so that I can reproduce the issue. In your case, they would be `control_statistics.cs` and `pypgx_results/output/read-depth.zip`, respectively. You can either upload them directly here or send them to me via email at sbstevenlee@gmail.com.

**Comment by sbslee** [comment]
@anh151,

Thanks for sending the files, I was able to reproduce the error!

The issue was certainly similar to #78 but more specific. Nevertheless, I was able to come up with a solution and the fix has been made in the `0.21.0-dev` branch. Could you please try it and see if it resolves the problem? You can locally install the development version:

```
$ git clone https://github.com/sbslee/pypgx
$ cd pypgx
$ git checkout 0.21.0-dev
$ pip install -e .
```

**Comment by anh151** [comment]
@sbslee 
That looks like it fixed the problem. Thanks for the quick replies!

**Comment by hongsheng-lai** [comment]
Dear @sbslee,
It seems like I encounter the same error in `0.21.0` version. I use `run-ngs-pipeline` cli after I use the variant calling you provide (`create-input-vcf`) in hg19.
I email the files for you to reproduce, please check out whenever you are available.

Error message:
```
[0;32;32mSaved VcfFrame[Imported] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/imported-variants.zip[0m
[0;32;32mSaved VcfFrame[Phased] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/phased-variants.zip[0m
[0;32;32mSaved VcfFrame[Consolidated] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/consolidated-variants.zip[0m
[0;32;32mSaved SampleTable[Alleles] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/alleles.zip[0m
[0;32;32mSaved CovFrame[ReadDepth] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/read-depth.zip[0m
[0;32;32mSaved CovFrame[CopyNumber] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/copy-number.zip[0m
[0;32;32mSaved SampleTable[CNVCalls] to: /volume/pgxdata/hprc_results/hprc.HG002.index_hs37d5.bwa/pypgx/UGT2B15/cnv-calls.zip[0m
Traceback (most recent call last):
  File "/usr/local/bin/pypgx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/usr/local/lib/python3.8/dist-packages/pypgx/cli/run_ngs_pipeline.py", line 159, in main
    pipeline.run_ngs_pipeline(
  File "/usr/local/lib/python3.8/dist-packages/pypgx/api/pipeline.py", line 301, in run_ngs_pipeline
    genotypes = genotype.call_genotypes(alleles=alleles, cnv_calls=cnv_calls)
  File "/usr/local/lib/python3.8/dist-packages/pypgx/api/genotype.py", line 622, in call_genotypes
    raise ValueError('SampleTable[Alleles] and '
ValueError: SampleTable[Alleles] and SampleTable[CNVCalls] have different samples
```

**Comment by sbslee** [comment]
@hongsheng-lai,

Thanks for sending the files. The problem was caused because the sample name in your VCF file  `hprc.HG002.index_hs37d5.bwa_pypgx.vcf.gz` (Name = `/volume/pgxdata/hprc/bam/hprc.HG002.index_hs37d5.bwa.bam`) is different from that of the `copy-number.zip` file (Name = `hprc.HG002.index_hs37d5.bwa`).

I've never seen this issue before, but my guess is that the sample name tag (`SM`) in your BAM is not properly set and that's why the file path or file name was used to represent sample name.

What's the output of:

```
$ fuc bam-head /volume/pgxdata/hprc/bam/hprc.HG002.index_hs37d5.bwa.bam
```

The `fuc` package should have been installed when you installed PyPGx. You could also simply use `samtools`:

```
$ samtools view -H /volume/pgxdata/hprc/bam/hprc.HG002.index_hs37d5.bwa.bam
```

**Comment by sbslee** [comment]
And I'm assuming you've used the same BAM for generating both input files?

**Comment by sbslee** [comment]
@hongsheng-lai,

Another user recently raised an issue (#105) that I think is related to your case:

> @muhligs,
> 
> Thanks for sending the header. As you can see, there is no read group tag (i.e. a line that starts with `@RG`) in the header, which should contain the sample name field (`SM`). You usually specify read group during the alignment step (when running `bwa mem` in your case). Additionally, I checked your attached files and, as speculated, the original BAM path was set as sample name.
> 
> Please add read group to your BAM to give a proper sample name and then run PyPGx on the new BAM. You can find more examples of read group in the Internet, but below is one example:
> 
> ```
> @RG ID:H0164.2  PL:illumina PU:H0164ALXX140820.2    LB:Solexa-272222    PI:0    DT:2014-08-20T00:00:00-0400 SM:NA12878  CN:BI
> ```


> FYI, you can easily add read group to existing BAM using existing tools like [samtools addreplacerg](http://www.htslib.org/doc/samtools-addreplacerg.html).

**Comment by hongsheng-lai** [comment]
It works! Thanks!
